### ISSUE TITLE
Request: make HR themeable so we can change its color

### ISSUE THREAD

**Issue by Jandoria** [stuyam/bootstrap-email#17]
Simple petition ;)

I've tried to put a custom class in the hr but with no luck.
```
.custom {
  border-top-color: #ff7700;
}
```

**Comment by stuyam** [comment]
You can 😄 just not obvious how. Since Bootstrap Email rewrites some of the html to work in all emails the `<hr>` is really a table. Whenever you want to overwrite a style take a look at how the current css works, here is the one for hr's: https://github.com/stuyam/bootstrap-email/blob/master/core/sass/_hr.scss

This worked for me in a simple test in the Bootstrap Editor: https://bootstrapemail.com/editor
```css
.hr td {
  border-top-color: red !important;
}
```

This will change the default for all of your hr's but you could do something like this if you want it to apply only to things you put the class on:
```css
.custom-hr td {
  border-top-color: red !important;
}
```
